### ISSUE TITLE
`mergeSort`, `insertionSort` and `quickSort` in   `/DOCUMENT/INT2PROGINATS/CODE/CHAP_DATAVTYPE` fails to build

### ISSUE THREAD

**Issue by bobajeff** [ats-lang/ats-lang.github.io#8]
Running `make` in `/DOCUMENT/INT2PROGINATS/CODE/CHAP_DATAVTYPE` fails to build on `mergeSort`

```console
$ make
/home/monkeykong/ats/tools/ATS2-Postiats-int-0.4.2/bin/patscc -o list_vt list_vt.dats
\
  /home/monkeykong/ats/tools/ATS2-Postiats-int-0.4.2/bin/patscc -DATS_MEMALLOC_LIBC -O2 -o rbtree rbtree.dats
\
  /home/monkeykong/ats/tools/ATS2-Postiats-int-0.4.2/bin/patscc -DATS_MEMALLOC_LIBC -O2 -o mergeSort mergeSort.dats
/home/monkeykong/ats/projects/ats-lang.github.io-master/DOCUMENT/INT2PROGINATS/CODE/CHAP_DATAVTYPE/mergeSort.dats: 3752(line=159, offs=10) -- 3774(line=159, offs=32): error(2): the dynamic identifier [list_vt_foreach_fun] is unrecognized.
patsopt(TRANS2): there are [1] errors in total.
exit(ATS): uncaught exception: _2tmp_2ATS_2dPostiats_2src_2pats_error_2esats__FatalErrorExn(1025)
make: *** [Makefile:31: mergeSort] Error 1
```
if I remove that rule it will fails on `insertionSort` and `quickSort` with the same error:

`the dynamic identifier [list_vt_foreach_fun] is unrecognized.`

**Comment by githwxi** [comment]
I took a quick look. I could compile these examples successfully.

The template list_vt_foreach_fun is defined in ATS-Postiats/libats/ML/DATS/atspre.dats.

**Comment by bobajeff** [comment]
You're right `list_vt_foreach_fun` is defined there in my installation of `ATS2-Postiats-int-0.4.2`! That's weird.  It still gives me the same error message.

I wonder what causing this on my installation. Most everything else seems to build fine. Here are the enviroment variable I have set in `~/.bashrc`:
```bash
export PATSHOME=/home/monkeykong/ats/tools/ATS2-Postiats-int-0.4.2
export PATSHOMERELOC=/home/monkeykong/ats/tools/ATS2-Postiats-contrib-0.4.2
export PATH=${PATSHOME}/bin:${PATH}
```
Am I missing any?

Should I have compiled `ATS2-Postiats-int-0.4.2` with the flags to run with garbage collection?

**Comment by bobajeff** [comment]
Thinking that there must be something wrong with my installation I decided to install it using the [recommended](https://github.com/ats-lang/ats-lang.github.io/tree/master/SCRIPT) build script here:
https://github.com/Hibou57/PostiATS-Utilities/blob/master/install-ats2-on-debian-ubuntu.sh

But It's still the same error message. (Without me manually loading  `atspre.sats` and `atspre.dats` inside the `mergeSort.dats` file)
```console
$ make
\
  /home/monkeykong/ats/ATS_INSTALL/lib/ats2-postiats-0.4.2/bin/patscc -DATS_MEMALLOC_LIBC -O2 -o mergeSort mergeSort.dats -latslib
/home/monkeykong/ats/projects/ats-lang.github.io-master/DOCUMENT/INT2PROGINATS/CODE/CHAP_ABSVTYPE/mergeSort.dats: 6200(line=244, offs=10) -- 6220(line=244, offs=30): error(2): the dynamic identifier [array_foreach_fun] is unrecognized.
patsopt(TRANS2): there are [1] errors in total.
exit(ATS): uncaught exception: _2tmp_2ATS_2dPostiats_2src_2pats_error_2esats__FatalErrorExn(1025)
make: *** [Makefile:21: mergeSort] Error 1

```

**Comment by bobajeff** [comment]
Running `make` in the other chapters I've found a couple more build failures:
`megasort` in [`/DOCUMENT/INT2PROGINATS/CODE/CHAP_ABSVTYPE/`](https://github.com/ats-lang/ats-lang.github.io/tree/master/DOCUMENT/INT2PROGINATS/CODE/CHAP_ABSVTYPE)
This time a different but very similar message `the dynamic identifier [array_foreach_fun] is unrecognized.`

```
$ make
\
  /home/monkeykong/ats/ATS_INSTALL4/ATS2/bin/patscc -DATS_MEMALLOC_LIBC -O2 -o mergeSort mergeSort.dats -latslib
/home/monkeykong/ats/projects/ats-lang.github.io/DOCUMENT/INT2PROGINATS/CODE/CHAP_ABSVTYPE/mergeSort.dats: 6115(line=241, offs=10) -- 6135(line=241, offs=30): error(2): the dynamic identifier [array_foreach_fun] is unrecognized.
patsopt(TRANS2): there are [1] errors in total.
exit(ATS): uncaught exception: _2home_2monkeykong_2ats_2ATS_INSTALL4_2ATS2_2src_2pats_error_2esats__FatalErrorExn(1025)
make: *** [Makefile:21: mergeSort] Error 1
```


and `gnumber` in[ `DOCUMENT/INT2PROGINATS/CODE/CHAP_FNTMPINT` ](https://github.com/ats-lang/ats-lang.github.io/tree/master/DOCUMENT/INT2PROGINATS/CODE/CHAP_FNTMPINT)fails with `[/home/monkeykong/ats/ATS_INSTALL4/ATS2/contrib/atscntrb-hx-intinf/DATS/intinf_t.dats] is not available for staloading.` That one is just a path issue here: https://github.com/ats-lang/ats-lang.github.io/blob/fe995415a474fb77c3965a41ac149dfd36f8e13b/DOCUMENT/INT2PROGINATS/CODE/CHAP_FNTMPINT/gnumber.dats#L127

and this file will also need to be changed:
https://github.com/githwxi/ATS-Postiats/blob/3e2cfab792d4d9f2598aca354297f06e5410b7df/contrib/atscntrb/atscntrb-hx-libgmp/SATS/gmp.sats#L41



```
$ make
/home/monkeykong/ats/ATS_INSTALL4/ATS2/bin/patscc -O2 -D_GNU_SOURCE -DATS_MEMALLOC_LIBC -o myprint myprint.dats -lgmp
\
/home/monkeykong/ats/ATS_INSTALL4/ATS2/bin/patscc -O2 -D_GNU_SOURCE -DATS_MEMALLOC_LIBC -I/home/monkeykong/ats/ATS_INSTALL4/ATS2/contrib -o gnumber gnumber.dats -lgmp
/home/monkeykong/ats/projects/ats-lang.github.io/DOCUMENT/INT2PROGINATS/CODE/CHAP_FNTMPINT/gnumber.dats: 2262(line=131, offs=1) -- 2312(line=132, offs=34): error(1): the file [/home/monkeykong/ats/ATS_INSTALL4/ATS2/contrib/atscntrb-hx-intinf/DATS/intinf_t.dats] is not available for staloading.
/home/monkeykong/ats/projects/ats-lang.github.io/DOCUMENT/INT2PROGINATS/CODE/CHAP_FNTMPINT/gnumber.dats: 2313(line=133, offs=1) -- 2365(line=134, offs=35): error(1): the file [/home/monkeykong/ats/ATS_INSTALL4/ATS2/contrib/atscntrb-hx-intinf/DATS/intinf_vt.dats] is not available for staloading.
/home/monkeykong/ats/projects/ats-lang.github.io/DOCUMENT/INT2PROGINATS/CODE/CHAP_FNTMPINT/gnumber.dats: 2369(line=136, offs=1) -- 2421(line=138, offs=35): error(1): the file [/home/monkeykong/ats/ATS_INSTALL4/ATS2/contrib/atscntrb-hx-intinf/DATS/gintinf_t.dats] is not available for staloading.
patsopt(TRANS1): there are [3] errors in total.
exit(ATS): uncaught exception: _2home_2monkeykong_2ats_2ATS_INSTALL4_2ATS2_2src_2pats_error_2esats__FatalErrorExn(1025)
make: *** [Makefile:34: gnumber] Error 1
```

**Comment by bobajeff** [comment]
It looks to me like this repository is use a old versions of the [CODE](https://github.com/ats-lang/ats-lang.github.io/tree/master/DOCUMENT/INT2PROGINATS/CODE) from this book and the more up to date ones are [here](https://github.com/githwxi/ATS-Postiats/tree/master/doc/BOOK/INT2PROGINATS/CODE) is [this repository](https://github.com/githwxi/ATS-Postiats) which all build correctly.

So I'm closing this as I think those are ones that are current and might explain why you were able to build on your system you must have been building from that repo instead.

I'd suggest removing these and/or updating the book to link to the up to date code to avoid confusion.

**Comment by githwxi** [comment]
Very sorry for this.

I just updated the CODE directory. It should work now.

ATS-Postiats is pretty much frozen at this point; its primary use is for implementing ATS-Xanadu
(ATS3), the next edition of ATS.
